export const CLIENT_PROFILES = [
  'ANDROID',
  'IOS',
  'WEB',
  'TVHTML5'
];

export const AUDIO_QUALITIES = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high'
};

export const ERROR_CODES = {
  VALIDATION_ERROR: 'ERR_VALIDATION',
  DECRYPTION_ERROR: 'ERR_DECRYPTION',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  RATE_LIMITED: 'ERR_RATE_LIMITED',
  NOT_FOUND: 'ERR_NOT_FOUND',
  UPSTREAM_ERROR: 'ERR_UPSTREAM',
  INTERNAL_ERROR: 'ERR_INTERNAL'
};
